In [8]:
import pandas as pd
from pathlib import Path

HOME_PATH = Path("..")

In [9]:
df = pd.read_csv(HOME_PATH / "data/dataset/AzharAli05_Resume_Screening_Dataset.csv")
df.head()

,role,resume,decision,reasoning,description
0,E-commerce Specialist,Jason Jones\nE-commerce Specialist\n\nContact ...,False,Lacked leadership skills for a senior position.,Be part of a passionate team at the forefront ...
1,E-commerce Specialist,Patricia Gray\nContact Information:\n\n* Email...,True,Impressive leadership and communication abilit...,Be part of a passionate team at the forefront ...
2,E-commerce Specialist,Amanda Gross\nContact Information:\n\n* Email:...,False,Lacked leadership skills for a senior position.,We are looking for an experienced E-commerce S...
3,Mobile App Developer,Jose Hall\nContact Information:\n\n* Email: [j...,False,No experience in back-end development.,We need a Mobile App Developer to enhance our ...
4,Cloud Engineer,Jessica Hall\nCloud Engineer\n\nContact Inform...,False,Needs improvement in machine learning algorithms.,We're seeking a talented Cloud Engineer to wor...

In [10]:
df['description'].sample(20, random_state=0)

311     As a System Administrator, you will play a piv...
154     As a Product Manager, you will play a pivotal ...
2027    Looking for an experienced Product Manager to ...
1687    Be part of a passionate team at the forefront ...
1519    We are looking for an experienced IT Support S...
2044    We are looking for an experienced Data Analyst...
4100    Be part of a passionate team at the forefront ...
4684    Help us build the next-generation products as ...
1881    Help us build the next-generation products as ...
1108    We are looking for an experienced Mobile App D...
125     Be part of a passionate team at the forefront ...
1939    Take the lead in driving innovation as a Softw...
1900    Be part of a passionate team at the forefront ...
49      As a Content Writer, you will play a pivotal r...
3985    Help us build the next-generation products as ...
534     We're seeking a talented QA Engineer to work o...
4452    We're seeking a talented Blockchain Developer ...
3278    Be part of a passionate team at the forefront ...
3863    Be part of a passionate team at the forefront ...
347     As a Data Architect, you will play a pivotal r...
Name: description, dtype: object

In [11]:
# grab ten random jobs
jobs = df['description'].drop_duplicates().sample(n=20, random_state=0)
jobs

56      We're seeking a talented Data Architect to wor...
421     We are looking for an experienced DevOps Engin...
322     Looking for an experienced Cloud Architect to ...
340     Take the lead in driving innovation as a Syste...
31      As a Data Engineer, you will play a pivotal ro...
509     Take the lead in driving innovation as a Block...
349     Be part of a passionate team at the forefront ...
415     Be part of a passionate team at the forefront ...
1509    As a Digital Marketing Specialist, you'll lead...
1543    As a AI Researcher, you will play a pivotal ro...
1024    If you're passionate about cloud technologies,...
1799    Looking for an experienced Cloud Engineer to j...
2409    As a Software Engineer, you will play a pivota...
682     We need a UX Designer to enhance our team's te...
4084    Join our fast-growing team and help us scale o...
1343    As a UX Designer, you will play a pivotal role...
285     As a Blockchain Developer, you'll lead the des...
161     We're hiring a E-commerce Specialist to develo...
718     Join our fast-growing team and help us scale o...
1517    We're hiring a Software Engineer to develop an...
Name: description, dtype: object

In [12]:
df = df[df['description'].isin(jobs)]
df = df.groupby(['description', 'decision'], group_keys=False).apply(lambda df: df.sample(n=1, random_state=0)).reset_index(drop=True)
df

/var/folders/z_/49jlm0q172zchrpp1qrxswc80000gn/T/ipykernel_77423/2742138597.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby(['description', 'decision'], group_keys=False).apply(lambda df: df.sample(n=1, random_state=0)).reset_index(drop=True)

,role,resume,decision,reasoning,description
0,AI Researcher,Darlene Williams\nContact Information:\n\n* Em...,False,No experience in back-end development.,"As a AI Researcher, you will play a pivotal ro..."
1,AI Researcher,Melanie Livingston\nAI Researcher\n\nContact I...,True,Impressive leadership and communication abilit...,"As a AI Researcher, you will play a pivotal ro..."
2,Blockchain Developer,April Rodriguez\nBlockchain Developer\n\nConta...,False,Lacked leadership skills for a senior position.,"As a Blockchain Developer, you'll lead the des..."
3,Blockchain Developer,Bethany Rodriguez\nContact Information:\n\n* P...,True,Excellent full-stack development experience.,"As a Blockchain Developer, you'll lead the des..."
4,Data Engineer,Alan Ross\nContact Information:\n\n* Email: [a...,False,Insufficient system design expertise for senio...,"As a Data Engineer, you will play a pivotal ro..."
5,Data Engineer,Tanner Harris\nData Engineer\n\nContact Inform...,True,Strong technical skills in AI and ML.,"As a Data Engineer, you will play a pivotal ro..."
6,Digital Marketing Specialist,Kristin Hamilton\nDigital Marketing Specialist...,False,Insufficient system design expertise for senio...,"As a Digital Marketing Specialist, you'll lead..."
7,Digital Marketing Specialist,Elizabeth Mccall\nContact Information:\n\n* Em...,True,Excellent full-stack development experience.,"As a Digital Marketing Specialist, you'll lead..."
8,Software Engineer,Emily Palmer\nSoftware Engineer\n\nContact Inf...,False,Lacks hands-on experience with cloud platforms.,"As a Software Engineer, you will play a pivota..."
9,Software Engineer,Renee Woods\nSoftware Engineer\n\nContact Info...,True,Solid experience in machine learning and AI.,"As a Software Engineer, you will play a pivota..."
10,UX Designer,Kristi Bryant\nUX Designer\n\nContact Informat...,False,Needs improvement in machine learning algorithms.,"As a UX Designer, you will play a pivotal role..."
11,UX Designer,Andrew Goodwin\nContact Information:\n\n* Phon...,True,Impressive leadership and communication abilit...,"As a UX Designer, you will play a pivotal role..."
12,Human Resources Specialist,Tammy Payne\nContact Information:\n\n* Address...,False,Insufficient system design expertise for senio...,Be part of a passionate team at the forefront ...
13,Human Resources Specialist,Travis Hamilton\nContact Information:\n\n* Add...,True,Strong technical skills in AI and ML.,Be part of a passionate team at the forefront ...
14,Content Writer,James Ramos\nContact Information:\n\n* Email: ...,False,Lacked leadership skills for a senior position.,Be part of a passionate team at the forefront ...
15,Content Writer,Desiree Gutierrez\nContact Information:\n\n* E...,True,Solid experience in machine learning and AI.,Be part of a passionate team at the forefront ...
16,QA Engineer,Alisha Graham\nContact Information:\n\n* Email...,False,Lacks hands-on experience with cloud platforms.,"If you're passionate about cloud technologies,..."
17,QA Engineer,Daniel Lopez\nContact Information:\n\n* Email:...,True,Strong technical skills in AI and ML.,"If you're passionate about cloud technologies,..."
18,Cloud Architect,Justin Peterson\nCloud Architect\n\nContact In...,False,Needs improvement in machine learning algorithms.,Join our fast-growing team and help us scale o...
19,Cloud Architect,Michael Powell\nCloud Architect\n\nContact Inf...,True,Solid experience in machine learning and AI.,Join our fast-growing team and help us scale o...
20,E-commerce Specialist,Jesse Martin\nContact Information:\n\n* Addres...,False,Insufficient system design expertise for senio...,Join our fast-growing team and help us scale o...
21,E-commerce Specialist,Stephen Lopez\nContact Information:\n\n* Addre...,True,Impressive leadership and communication abilit...,Join our fast-growing team and help us scale o...
22,Cloud Architect,Jamie Rowe\nCloud Architect\n\nContact Informa...,False,Lacks hands-on experience with cloud platforms.,Looking for an experienced Cloud Architect to ...
23,Cloud Architect,Jason Ward\nCloud Architect\n\nContact Informa...,True,Excellent full-stack development experience.,Looking for an experienced Cloud Architect to ...
24,Cloud Engineer,Dominique Brewer\nCloud Engineer\n\nContact In...,False,Lacks hands-on experience with cloud platforms.,Looking for an experienced Cloud Engineer to j...
25,Cloud Engineer,Cynthia Norman\nCloud Engineer\n\nContact Info...,True,Impressive leadership and communication abilit...,Looking for an experienced Cloud Engineer to j...
26,Blockchain Developer,Amanda Madden\nBlockchain Developer\n\nContact...,False,Insufficient system design expertise for senio...,Take the lead in driving innovation as a Block...
27,Blockchain Developer,Michael Andrade\nBlockchain Developer\n\nConta...,True,Strong technical skills in AI and ML.,Take the lead in driving innovation as a Block...
28,System Administrator,Benjamin Rogers\nSystem Administrator\n\nConta...,False,Insufficient system design expertise for senio...,Take the lead in driving innovation as a Syste...
29,System Administrator,Michael Yu\nSystem Administrator\n\nContact In...,True,Excellent full-stack development experience.,Take the lead in driving innovation as a Syste...
30,DevOps Engineer,Francisco Werner\nContact Information:\n\n* Ph...,False,Insufficient system design expertise for senio...,We are looking for an experienced DevOps Engin...
31,DevOps Engineer,Margaret Russell\nDevOps Engineer\n\nContact I...,True,Solid experience in machine learning and AI.,We are looking for an experienced DevOps Engin...
32,UX Designer,Andre Erickson\nUX Designer\n\nContact Informa...,False,No experience in back-end development.,We need a UX Designer to enhance our team's te...
33,UX Designer,Colleen Rodriguez\nUX Designer\n\nContact Info...,True,Perfectly aligned with data engineering needs.,We need a UX Designer to enhance our team's te...
34,E-commerce Specialist,Lynn Hughes\nE-commerce Specialist\n\nContact ...,False,Insufficient system design expertise for senio...,We're hiring a E-commerce Specialist to develo...
35,E-commerce Specialist,Shelley Brown\nE-commerce Specialist\n\nContac...,True,Strong technical skills in AI and ML.,We're hiring a E-commerce Specialist to develo...
36,Software Engineer,Michele Floyd\nSoftware Engineer\n\nContact In...,False,No experience in back-end development.,We're hiring a Software Engineer to develop an...
37,Software Engineer,Rebecca Wilcox\nSoftware Engineer\n\nContact I...,True,Impressive leadership and communication abilit...,We're hiring a Software Engineer to develop an...
38,Data Architect,Debra Brown\nData Architect\n\nContact Informa...,False,Lacked leadership skills for a senior position.,We're seeking a talented Data Architect to wor...
39,Data Architect,Antonio Turner\nContact Information:\n\n* Emai...,True,Solid experience in machine learning and AI.,We're seeking a talented Data Architect to wor...

In [13]:
# let's convert this to a "standard form"
new_dict = [
    {
        'description': d,
        'resume_accept': df[
            (df['description']==d) & (df['decision']==True)
        ]['resume'].item(),
        'resume_reject': df[
            (df['description']==d) & (df['decision']==False)
        ]['resume'].item(),
    } for d in df['description'].unique()
]
df_2 = pd.DataFrame(new_dict)
df_2

,description,resume_accept,resume_reject
0,"As a AI Researcher, you will play a pivotal ro...",Melanie Livingston\nAI Researcher\n\nContact I...,Darlene Williams\nContact Information:\n\n* Em...
1,"As a Blockchain Developer, you'll lead the des...",Bethany Rodriguez\nContact Information:\n\n* P...,April Rodriguez\nBlockchain Developer\n\nConta...
2,"As a Data Engineer, you will play a pivotal ro...",Tanner Harris\nData Engineer\n\nContact Inform...,Alan Ross\nContact Information:\n\n* Email: [a...
3,"As a Digital Marketing Specialist, you'll lead...",Elizabeth Mccall\nContact Information:\n\n* Em...,Kristin Hamilton\nDigital Marketing Specialist...
4,"As a Software Engineer, you will play a pivota...",Renee Woods\nSoftware Engineer\n\nContact Info...,Emily Palmer\nSoftware Engineer\n\nContact Inf...
5,"As a UX Designer, you will play a pivotal role...",Andrew Goodwin\nContact Information:\n\n* Phon...,Kristi Bryant\nUX Designer\n\nContact Informat...
6,Be part of a passionate team at the forefront ...,Travis Hamilton\nContact Information:\n\n* Add...,Tammy Payne\nContact Information:\n\n* Address...
7,Be part of a passionate team at the forefront ...,Desiree Gutierrez\nContact Information:\n\n* E...,James Ramos\nContact Information:\n\n* Email: ...
8,"If you're passionate about cloud technologies,...",Daniel Lopez\nContact Information:\n\n* Email:...,Alisha Graham\nContact Information:\n\n* Email...
9,Join our fast-growing team and help us scale o...,Michael Powell\nCloud Architect\n\nContact Inf...,Justin Peterson\nCloud Architect\n\nContact In...
10,Join our fast-growing team and help us scale o...,Stephen Lopez\nContact Information:\n\n* Addre...,Jesse Martin\nContact Information:\n\n* Addres...
11,Looking for an experienced Cloud Architect to ...,Jason Ward\nCloud Architect\n\nContact Informa...,Jamie Rowe\nCloud Architect\n\nContact Informa...
12,Looking for an experienced Cloud Engineer to j...,Cynthia Norman\nCloud Engineer\n\nContact Info...,Dominique Brewer\nCloud Engineer\n\nContact In...
13,Take the lead in driving innovation as a Block...,Michael Andrade\nBlockchain Developer\n\nConta...,Amanda Madden\nBlockchain Developer\n\nContact...
14,Take the lead in driving innovation as a Syste...,Michael Yu\nSystem Administrator\n\nContact In...,Benjamin Rogers\nSystem Administrator\n\nConta...
15,We are looking for an experienced DevOps Engin...,Margaret Russell\nDevOps Engineer\n\nContact I...,Francisco Werner\nContact Information:\n\n* Ph...
16,We need a UX Designer to enhance our team's te...,Colleen Rodriguez\nUX Designer\n\nContact Info...,Andre Erickson\nUX Designer\n\nContact Informa...
17,We're hiring a E-commerce Specialist to develo...,Shelley Brown\nE-commerce Specialist\n\nContac...,Lynn Hughes\nE-commerce Specialist\n\nContact ...
18,We're hiring a Software Engineer to develop an...,Rebecca Wilcox\nSoftware Engineer\n\nContact I...,Michele Floyd\nSoftware Engineer\n\nContact In...
19,We're seeking a talented Data Architect to wor...,Antonio Turner\nContact Information:\n\n* Emai...,Debra Brown\nData Architect\n\nContact Informa...

In [14]:
df_2.to_csv(HOME_PATH / "data/dataset/AzharAli05_Resume_subset.csv", index=False)