In [1]:
import pandas as pd
from pathlib import Path

HOME_PATH = Path("..")

In [2]:
df = pd.read_csv(HOME_PATH / "data/dataset/AzharAli05_Resume_Screening_Dataset.csv")
df.head()

,role,resume,decision,reasoning,description
0,E-commerce Specialist,Jason Jones\nE-commerce Specialist\n\nContact ...,False,Lacked leadership skills for a senior position.,Be part of a passionate team at the forefront ...
1,E-commerce Specialist,Patricia Gray\nContact Information:\n\n* Email...,True,Impressive leadership and communication abilit...,Be part of a passionate team at the forefront ...
2,E-commerce Specialist,Amanda Gross\nContact Information:\n\n* Email:...,False,Lacked leadership skills for a senior position.,We are looking for an experienced E-commerce S...
3,Mobile App Developer,Jose Hall\nContact Information:\n\n* Email: [j...,False,No experience in back-end development.,We need a Mobile App Developer to enhance our ...
4,Cloud Engineer,Jessica Hall\nCloud Engineer\n\nContact Inform...,False,Needs improvement in machine learning algorithms.,We're seeking a talented Cloud Engineer to wor...

In [3]:
df['description'].sample(5, random_state=0)

311     As a System Administrator, you will play a piv...
154     As a Product Manager, you will play a pivotal ...
2027    Looking for an experienced Product Manager to ...
1687    Be part of a passionate team at the forefront ...
1519    We are looking for an experienced IT Support S...
Name: description, dtype: object

In [4]:
# grab ten random jobs
jobs = df['description'].drop_duplicates().sample(n=5, random_state=0)
jobs

56     We're seeking a talented Data Architect to wor...
421    We are looking for an experienced DevOps Engin...
322    Looking for an experienced Cloud Architect to ...
340    Take the lead in driving innovation as a Syste...
31     As a Data Engineer, you will play a pivotal ro...
Name: description, dtype: object

In [5]:
df = df[df['description'].isin(jobs)]
df = df.groupby(['description', 'decision'], group_keys=False).apply(lambda df: df.sample(n=1, random_state=0)).reset_index(drop=True)
df

C:\Users\dyaom\AppData\Local\Temp\ipykernel_9208\2742138597.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby(['description', 'decision'], group_keys=False).apply(lambda df: df.sample(n=1, random_state=0)).reset_index(drop=True)

,role,resume,decision,reasoning,description
0,Data Engineer,Alan Ross\nContact Information:\n\n* Email: [a...,False,Insufficient system design expertise for senio...,"As a Data Engineer, you will play a pivotal ro..."
1,Data Engineer,Tanner Harris\nData Engineer\n\nContact Inform...,True,Strong technical skills in AI and ML.,"As a Data Engineer, you will play a pivotal ro..."
2,Cloud Architect,Jamie Rowe\nCloud Architect\n\nContact Informa...,False,Lacks hands-on experience with cloud platforms.,Looking for an experienced Cloud Architect to ...
3,Cloud Architect,Jason Ward\nCloud Architect\n\nContact Informa...,True,Excellent full-stack development experience.,Looking for an experienced Cloud Architect to ...
4,System Administrator,Benjamin Rogers\nSystem Administrator\n\nConta...,False,Insufficient system design expertise for senio...,Take the lead in driving innovation as a Syste...
5,System Administrator,Michael Yu\nSystem Administrator\n\nContact In...,True,Excellent full-stack development experience.,Take the lead in driving innovation as a Syste...
6,DevOps Engineer,Francisco Werner\nContact Information:\n\n* Ph...,False,Insufficient system design expertise for senio...,We are looking for an experienced DevOps Engin...
7,DevOps Engineer,Margaret Russell\nDevOps Engineer\n\nContact I...,True,Solid experience in machine learning and AI.,We are looking for an experienced DevOps Engin...
8,Data Architect,Debra Brown\nData Architect\n\nContact Informa...,False,Lacked leadership skills for a senior position.,We're seeking a talented Data Architect to wor...
9,Data Architect,Antonio Turner\nContact Information:\n\n* Emai...,True,Solid experience in machine learning and AI.,We're seeking a talented Data Architect to wor...

In [6]:
# let's convert this to a "standard form"
new_dict = [
    {
        'description': d,
        'resume_accept': df[
            (df['description']==d) & (df['decision']==True)
        ]['resume'].item(),
        'resume_reject': df[
            (df['description']==d) & (df['decision']==False)
        ]['resume'].item(),
    } for d in df['description'].unique()
]
df_2 = pd.DataFrame(new_dict)
df_2

,description,resume_accept,resume_reject
0,"As a Data Engineer, you will play a pivotal ro...",Tanner Harris\nData Engineer\n\nContact Inform...,Alan Ross\nContact Information:\n\n* Email: [a...
1,Looking for an experienced Cloud Architect to ...,Jason Ward\nCloud Architect\n\nContact Informa...,Jamie Rowe\nCloud Architect\n\nContact Informa...
2,Take the lead in driving innovation as a Syste...,Michael Yu\nSystem Administrator\n\nContact In...,Benjamin Rogers\nSystem Administrator\n\nConta...
3,We are looking for an experienced DevOps Engin...,Margaret Russell\nDevOps Engineer\n\nContact I...,Francisco Werner\nContact Information:\n\n* Ph...
4,We're seeking a talented Data Architect to wor...,Antonio Turner\nContact Information:\n\n* Emai...,Debra Brown\nData Architect\n\nContact Informa...

In [7]:
df_2.to_csv(HOME_PATH / "data/dataset/AzharAli05_Resume_subset.csv", index=False)