In [15]:
import pandas as pd
from pathlib import Path

HOME_PATH = Path("..")

In [16]:
df = pd.read_csv(HOME_PATH / "data/dataset/AzharAli05_Resume_Screening_Dataset.csv")
df.head()

,role,resume,decision,reasoning,description
0,E-commerce Specialist,Jason Jones\nE-commerce Specialist\n\nContact ...,False,Lacked leadership skills for a senior position.,Be part of a passionate team at the forefront ...
1,E-commerce Specialist,Patricia Gray\nContact Information:\n\n* Email...,True,Impressive leadership and communication abilit...,Be part of a passionate team at the forefront ...
2,E-commerce Specialist,Amanda Gross\nContact Information:\n\n* Email:...,False,Lacked leadership skills for a senior position.,We are looking for an experienced E-commerce S...
3,Mobile App Developer,Jose Hall\nContact Information:\n\n* Email: [j...,False,No experience in back-end development.,We need a Mobile App Developer to enhance our ...
4,Cloud Engineer,Jessica Hall\nCloud Engineer\n\nContact Inform...,False,Needs improvement in machine learning algorithms.,We're seeking a talented Cloud Engineer to wor...

In [18]:
df['description'].sample(150, random_state=0)

311     As a System Administrator, you will play a piv...
154     As a Product Manager, you will play a pivotal ...
2027    Looking for an experienced Product Manager to ...
1687    Be part of a passionate team at the forefront ...
1519    We are looking for an experienced IT Support S...
                              ...
1620    Help us build the next-generation products as ...
2367    We're seeking a talented AI Researcher to work...
727     We need a Digital Marketing Specialist to enha...
507     As a Business Analyst, you'll lead the design ...
2810    We need a Mobile App Developer to enhance our ...
Name: description, Length: 150, dtype: object

In [19]:
# grab ten random jobs
jobs = df['description'].drop_duplicates().sample(n=150, random_state=0)
jobs

56      We're seeking a talented Data Architect to wor...
421     We are looking for an experienced DevOps Engin...
322     Looking for an experienced Cloud Architect to ...
340     Take the lead in driving innovation as a Syste...
31      As a Data Engineer, you will play a pivotal ro...
                              ...
3697    We are looking for an experienced Blockchain D...
169     We are looking for an experienced Data Analyst...
244     We need a Digital Marketing Specialist to enha...
425     Take the lead in driving innovation as a AI Re...
471     We're seeking a talented Cloud Architect to wo...
Name: description, Length: 150, dtype: object

In [20]:
df = df[df['description'].isin(jobs)]
df = df.groupby(['description', 'decision'], group_keys=False).apply(lambda df: df.sample(n=1, random_state=0)).reset_index(drop=True)
df

/var/folders/z_/49jlm0q172zchrpp1qrxswc80000gn/T/ipykernel_77423/2742138597.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby(['description', 'decision'], group_keys=False).apply(lambda df: df.sample(n=1, random_state=0)).reset_index(drop=True)

,role,resume,decision,reasoning,description
0,AI Researcher,Erin Kelly\nContact Information:\n\n* Email: [...,False,Needs improvement in machine learning algorithms.,"As a AI Researcher, you will play a pivotal ro..."
1,AI Researcher,Jason Foster\nAI Researcher\n\nContact Informa...,True,Excellent full-stack development experience.,"As a AI Researcher, you will play a pivotal ro..."
2,AI Researcher,Darlene Williams\nContact Information:\n\n* Em...,False,No experience in back-end development.,"As a AI Researcher, you will play a pivotal ro..."
3,AI Researcher,Melanie Livingston\nAI Researcher\n\nContact I...,True,Impressive leadership and communication abilit...,"As a AI Researcher, you will play a pivotal ro..."
4,AI Researcher,John Yang\nAI Researcher\n\nContact Informatio...,False,Lacks hands-on experience with cloud platforms.,"As a AI Researcher, you'll lead the design and..."
...,...,...,...,...,...
295,Human Resources Specialist,Justin Hanson\nHuman Resources Specialist\n\nC...,True,Strong technical skills in AI and ML.,We're seeking a talented Human Resources Speci...
296,Machine Learning Engineer,Elizabeth Velasquez\nContact Information:\n\n*...,False,Insufficient system design expertise for senio...,We're seeking a talented Machine Learning Engi...
297,Machine Learning Engineer,Scott Hill\nContact Information:\n\n* Email: [...,True,Excellent full-stack development experience.,We're seeking a talented Machine Learning Engi...
298,Product Manager,Jeffrey Smith\nContact Information:\n\n* Phone...,False,No experience in back-end development.,We're seeking a talented Product Manager to wo...
299,Product Manager,Matthew Morgan\nContact Information:\n\n* Emai...,True,Perfectly aligned with data engineering needs.,We're seeking a talented Product Manager to wo...

In [21]:
# let's convert this to a "standard form"
new_dict = [
    {
        'description': d,
        'resume_accept': df[
            (df['description']==d) & (df['decision']==True)
        ]['resume'].item(),
        'resume_reject': df[
            (df['description']==d) & (df['decision']==False)
        ]['resume'].item(),
    } for d in df['description'].unique()
]
df_2 = pd.DataFrame(new_dict)
df_2

,description,resume_accept,resume_reject
0,"As a AI Researcher, you will play a pivotal ro...",Jason Foster\nAI Researcher\n\nContact Informa...,Erin Kelly\nContact Information:\n\n* Email: [...
1,"As a AI Researcher, you will play a pivotal ro...",Melanie Livingston\nAI Researcher\n\nContact I...,Darlene Williams\nContact Information:\n\n* Em...
2,"As a AI Researcher, you'll lead the design and...",Howard Carter\nContact Information:\n\n* Email...,John Yang\nAI Researcher\n\nContact Informatio...
3,"As a AI Researcher, you'll lead the design and...",Amber Henderson\nAI Researcher\n\nContact Info...,Andrew Hicks\nContact Information:\n\n* Email:...
4,"As a AI Researcher, you'll lead the design and...",Jennifer Sanford\nAI Researcher\n\nContact Inf...,Lisa Flores\nContact Information:\n\n* Email: ...
...,...,...,...
145,We're seeking a talented Data Scientist to wor...,Dawn Tucker\nData Scientist\n\nContact Informa...,Justin Taylor\nData Scientist\n\nContact Infor...
146,We're seeking a talented Full Stack Developer ...,Stephanie Lopez\nContact Information:\n\n* Ema...,Jeffrey Simpson\nFull Stack Developer\n\nConta...
147,We're seeking a talented Human Resources Speci...,Justin Hanson\nHuman Resources Specialist\n\nC...,Dr. Jessica Montgomery\nHuman Resources Specia...
148,We're seeking a talented Machine Learning Engi...,Scott Hill\nContact Information:\n\n* Email: [...,Elizabeth Velasquez\nContact Information:\n\n*...
149,We're seeking a talented Product Manager to wo...,Matthew Morgan\nContact Information:\n\n* Emai...,Jeffrey Smith\nContact Information:\n\n* Phone...

In [22]:
df_2.to_csv(HOME_PATH / "data/dataset/AzharAli05_Resume_subset150.csv", index=False)